### ISSUE TITLE
Is support django2.0?

### ISSUE THREAD

**Issue by 625781186** [jazzband/django-mongonaut#104]
### I found update this repository , but error occur to me .

![image](https://user-images.githubusercontent.com/30521429/58068009-2e2bb900-7bc2-11e9-9191-673c4ed97ffd.png)

error:
```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x05C12780>
Traceback (most recent call last):
  File "D:\CodePro\py_c\_Envs\dj2\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "D:\CodePro\py_c\_Envs\dj2\lib\site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "D:\CodePro\py_c\_Envs\dj2\lib\site-packages\django\core\management\base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "D:\CodePro\py_c\_Envs\dj2\lib\site-packages\django\core\management\base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "D:\CodePro\py_c\_Envs\dj2\lib\site-packages\django\core\checks\registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "D:\CodePro\py_c\_Envs\dj2\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "D:\CodePro\py_c\_Envs\dj2\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "D:\CodePro\py_c\_Envs\dj2\lib\site-packages\django\urls\resolvers.py", line 396, in check
    for pattern in self.url_patterns:
  File "D:\CodePro\py_c\_Envs\dj2\lib\site-packages\django\utils\functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\CodePro\py_c\_Envs\dj2\lib\site-packages\django\urls\resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\CodePro\py_c\_Envs\dj2\lib\site-packages\django\utils\functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\CodePro\py_c\_Envs\dj2\lib\site-packages\django\urls\resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "D:\CodePro\py_c\_Envs\dj2\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "G:\BaiduYunDownload\教程\django\Vue+Django REST framework 打造生鲜电商项目\book_serve\book_serve\urls.py", line 22, in <module>
    path('mongonaut/', include('mongonaut.urls')),
  File "D:\CodePro\py_c\_Envs\dj2\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "D:\CodePro\py_c\_Envs\dj2\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\CodePro\py_c\_Envs\dj2\lib\site-packages\mongonaut\urls.py", line 1, in <module>
    from django.conf.urls import patterns, url
ImportError: cannot import name 'patterns'
```

modules version :
```
Django              2.1.5
django-mongonaut    0.2.21
mongoengine         0.17.0
```

**Comment by garrypolley** [comment]
Currently the project has not been updated for newer versions of Django. 

The `patterns` import has been deprecated: https://docs.djangoproject.com/en/1.9/ref/urls/#patterns

**Comment by 625781186** [comment]
> Currently the project has not been updated for newer versions of Django.
> 
> The `patterns` import has been deprecated: https://docs.djangoproject.com/en/1.9/ref/urls/#patterns

So currently the project just support  django's version <1.9 ?

**Comment by Provoo** [comment]
You should help us, upgrading for django 2.0 please, I think is a great product, and we can't use because this bug.

**Comment by CARocha** [comment]
this is the problem!! :/

Continued maintainance is at risk!
There are no members yet who have volunteered to lead this project.

for Jazzband https://jazzband.co/projects/django-mongonaut
